{% set name = "odc-cloud" %}
{% set version = "0.2.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: d33222ff953d3c365fcae72465854ccda293394938427e5a686967b399ddd1ce

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - botocore
    - boto3

test:
  imports:
    - odc
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/opendatacube/odc-tools/
  summary: Various AWS helper methods
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - SpacemanPaul
    - Ariana-B
