{% set name = "odc-cloud" %}
{% set version = "0.2.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/odc-cloud-{{ version }}.tar.gz
  sha256: ec5ad436b89ddadc5cd13ef7dac8b15d7b49fc4c9f1d939e1915696f169981f9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - botocore
    - boto3

test:
  imports:
    - odc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/opendatacube/odc-tools/
  summary: Various AWS helper methods
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Ariana-B
