{% set name = "odc-cloud" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/odc-cloud-{{ version }}.tar.gz
  sha256: 44bb07b90f425c24aee0f300e5b1fc687b1f0bb62d3854738915abd8f262c144

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - botocore
    - boto3
    - aiobotocore

test:
  imports:
    - odc.aws
    - odc.cloud
    - odc.aio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/opendatacube/odc-tools/
  summary: Various AWS helper methods
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Ariana-B
    - omad
    - SpacemanPaul
